//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebBancos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sucursal", Namespace="http://schemas.datacontract.org/2004/07/ServicioBanco")]
    [System.SerializableAttribute()]
    public partial class Sucursal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBanco {
            get {
                return this.IdBancoField;
            }
            set {
                if ((this.IdBancoField.Equals(value) != true)) {
                    this.IdBancoField = value;
                    this.RaisePropertyChanged("IdBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebServiceOperacionesBanco")]
    public interface IWebServiceOperacionesBanco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceOperacionesBanco/DoWork", ReplyAction="http://tempuri.org/IWebServiceOperacionesBanco/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceOperacionesBanco/DoWork", ReplyAction="http://tempuri.org/IWebServiceOperacionesBanco/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceOperacionesBanco/ObtenerSucursalPorBanco", ReplyAction="http://tempuri.org/IWebServiceOperacionesBanco/ObtenerSucursalPorBancoResponse")]
        AppWebBancos.ServiceReference1.Sucursal[] ObtenerSucursalPorBanco(int IdBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceOperacionesBanco/ObtenerSucursalPorBanco", ReplyAction="http://tempuri.org/IWebServiceOperacionesBanco/ObtenerSucursalPorBancoResponse")]
        System.Threading.Tasks.Task<AppWebBancos.ServiceReference1.Sucursal[]> ObtenerSucursalPorBancoAsync(int IdBanco);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceOperacionesBancoChannel : AppWebBancos.ServiceReference1.IWebServiceOperacionesBanco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceOperacionesBancoClient : System.ServiceModel.ClientBase<AppWebBancos.ServiceReference1.IWebServiceOperacionesBanco>, AppWebBancos.ServiceReference1.IWebServiceOperacionesBanco {
        
        public WebServiceOperacionesBancoClient() {
        }
        
        public WebServiceOperacionesBancoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceOperacionesBancoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceOperacionesBancoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceOperacionesBancoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public AppWebBancos.ServiceReference1.Sucursal[] ObtenerSucursalPorBanco(int IdBanco) {
            return base.Channel.ObtenerSucursalPorBanco(IdBanco);
        }
        
        public System.Threading.Tasks.Task<AppWebBancos.ServiceReference1.Sucursal[]> ObtenerSucursalPorBancoAsync(int IdBanco) {
            return base.Channel.ObtenerSucursalPorBancoAsync(IdBanco);
        }
    }
}
